export const USER_CLIENT = Symbol('USER_CLIENT_SERVICE')
export const NOTIFICATION_CLIENT = Symbol('NOTIFICATION_CLIENT_SERVICE')
export const SERVICE_CATEGORY_CLIENT = Symbol('SERVICE_CATEGORY_CLIENT_SERVICE')
export const SERVICE_SUB_CATEGORY_CLIENT = Symbol('SERVICE_SUB_CATEGORY_CLIENT_SERVICE')
export const SERVICE_CLIENT = Symbol('SERVICE_CLIENT_SERVICE')
export const FEES_CLIENT = Symbol('FEES_CLIENT_SERVICE')
export const FEATUREDPLAN_CLIENT = Symbol('FEATUREDPLAN_CLIENT_SERVICE')


